# SPDX-FileCopyrightText: 2025 Felix Hilgers <felix.hilgers@fau.de>
#
# SPDX-License-Identifier: MIT

[target.'cfg(not(target_arch = "bpf"))']
rustflags = ["-C", "linker-plugin-lto", "-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

[target.'cfg(target_arch = "bpf")']
rustflags = ["-C", "debuginfo=2", "-C", "debug-assertions=false"]

[alias]
ebpf = "build -Zbuild-std=core --bin ebpf-refactored --target bpfeb-unknown-none --target bpfel-unknown-none --release"