# SPDX-FileCopyrightText: 2024 Felix Hilgers <felix.hilgers@fau.de>
#
# SPDX-License-Identifier: MIT

name: "Setup Gradle Cache"
description: "Sets up a cache for Gradle builds"

inputs:
  accessKey:
    required: true
  secretKey:
    required: true

runs:
  using: "composite"
  steps:
    - uses: tespkg/actions-cache@v1
      with:
        path: |
          frontend/.gradle
        key: ${{ github.repository }}-${{ runner.os }}-gradle-${{ github.job }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ github.repository }}-${{ runner.os }}-gradle-
        bucket: actions-cache
        accessKey: ${{ inputs.accessKey }}
        secretKey: ${{ inputs.secretKey }}
        endpoint: localhost
        port: 9000
        insecure: true
        use-fallback: false
