# SPDX-FileCopyrightText: 2024 Felix Hilgers <felix.hilgers@fau.de>
#
# SPDX-License-Identifier: MIT

name: "Setup Rust"
description: "Sets up a rust action"

inputs:
  accessKey:
    required: true
  secretKey:
    required: true
  cacheKey:
    required: false

runs:
  using: "composite"
  steps:
    - uses: tespkg/actions-cache@v1
      with:
        path: |
          rust/target
        key: ${{ github.repository }}-${{ runner.os }}-cargo-${{ github.job }}-${{ inputs.cacheKey }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ github.repository }}-${{ runner.os }}-cargo-${{ github.job }}-${{ inputs.cacheKey }}-
        bucket: actions-cache
        accessKey: ${{ inputs.accessKey }}
        secretKey: ${{ inputs.secretKey }}
        endpoint: localhost
        port: 9000
        insecure: true
        use-fallback: false
