# SPDX-FileCopyrightText: 2024 Felix Hilgers <felix.hilgers@fau.de>
#
# SPDX-License-Identifier: MIT

name: Docker Build and Push

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Restore and cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        run: |
          nix run .#dockerBuilder.copyTo -- docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest --digestfile digest.txt 
          echo "digest=$(cat digest.txt)" >> $GITHUB_OUTPUT

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest}}
          push-to-registry: true