# SPDX-FileCopyrightText: 2024 Felix Hilgers <felix.hilgers@fau.de>
#
# SPDX-License-Identifier: MIT

name: Lint, Build, Test

on:
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  
  reuse-lint:
    name: Reuse Lint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-base

      - name: Lint
        run: nix run .#reuseLint
        
  gradle-lint:
    name: Gradle Lint
    runs-on: ubuntu-24.04
    needs: [reuse-lint]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-base
      - uses: ./.github/actions/setup-gradle-cache
        
      - name: Lint
        run: nix run .#gradleLint
        
    
  rust-lint:
    name: Rust Lint
    runs-on: ubuntu-24.04
    needs: [reuse-lint]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-base
      - uses: ./.github/actions/setup-rust-cache
        
      - name: Lint
        run: nix run .#rustLint
        
  gradle-build-test:
    name: Gradle Test
    runs-on: ubuntu-24.04
    needs: gradle-lint

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-base
      - uses: ./.github/actions/setup-gradle-cache
        
      - name: Build and Test
        run: nix run .#gradleTest
        
  rust-build-test:
    name: Rust Test
    runs-on: ubuntu-24.04
    needs: rust-lint

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-base
      - uses: ./.github/actions/setup-rust-cache
        
      - name: Build and Test
        run: nix run .#rustTest